### PR TITLE
Clifford

### LINKED ISSUE #6: Exercise 1 Task 2: Create a function to calculate metrics required by the Bland and Altman plot
Create a function that will calculate the following metrics required by the **Bland and Altman plot** as described in the article:

* [ ] Mean of the per subject measurements made by the Wright and the Mini-Wright;
    
* [x] Difference between the per subject measurements made by the Wright and the Mini-Wright;
    
* [x] Mean of the difference between the per subject measurements made by the Wright and the Mini-Wright; and,
    
* [x] Lower and upper limits of agreement between the per subject measurements made by the Wright and the Mini-Wright.

### PR DESCRIPTION
**Pull request by clicoselis**
team naruto's suggested code

### CODE REVIEW

**Review by ernestguevarra — CHANGES_REQUESTED** [review]
@clicoselis great work.

Good function specification. Well done.

I am just going to push you a little bit further here and comment on the following:

* in general, our conventions when reporting estimates with confidence intervals is to report the estimate first and then followed by lower limit and then upper limit. So in your line for the `return` in the function, I would suggest something like this:

```R
return(c(mean_difference, lower_limit, upper_limit))
```

* I know I said yesterday that you don't need the mean of the two values for Wright and Mini respectively. However, I realised when I was reviewing the Exercise that you do need that value alongside the difference in values for the next question asking for a function to create a Bland and Altman plot.

So I would recommend that in your function you calculate the mean of the two values, the difference, the mean difference and the limits of agreement. I would also recommend to change your line for the `return` function into something like this:

```R
return(list(mean_measurement, differences, mean_difference, lower_limit, upper_limit))
```

**Comment by ernestguevarra** [comment]
@JosephineCarenNdawula I have added you as a reviewer for this pull request. We will wait for your review before we make a decision on whether we merge this in or not.

**Review by ernestguevarra — COMMENTED** [review]
@clicoselis thanks for doing that and addressing the feedback.

I will wait for @JosephineCarenNdawula review before we make a decision on whether to merge this to main.

**Review by ernestguevarra — APPROVED** [review]

**Comment by ernestguevarra** [comment]
@clicoselis, we've not heard from @JosephineCarenNdawula. She doesn't have a branch here as well so maybe she is busy.

I have approved your changes! Well done! Please merge to main at your convenience.

**Comment by JosephineCarenNdawula** [comment]
Dear Ernest,

I was unwell but also locked out of Oxford SSO because my phone was in
repairs so I couldn't attend our last class online and therefore follow the
proceedings from it.

I apologize for the inconvenience this caused and I'm making efforts to
catch up.

Sincerely,
Josephine.

**Pull request merged**
