### PR TITLE
Mariano

### PR DESCRIPTION
**Pull request by marianortt**
Task 2 done

### CODE REVIEW

**Comment by ernestguevarra** [comment]
@marianortt, I will ask someone else to review your work. @naemiamanuel, can you review Mariano's current pull request for addressing exercise 1 task number 2? Try to follow as much as you can the review process I showed in class. If in doubt, let me know and I will guide you.

Also, I remember now why I asked you guys to calculate the mean of the two measurements per subject. This will be evident to you in task 3 when you create a Bland and Altman plot.

**Review by ernestguevarra — COMMENTED** [review]
awaiting review from @naemiamanuel.

**Review by naemiamanuel — COMMENTED** [review]
The code looks good to me. I am not quiet sure if the functions you used are built-in R. So prehaps think about stating which package or library you used.

**Comment by ernestguevarra** [comment]
> The code looks good to me. I am not quiet sure if the functions you used are built-in R. So prehaps think about stating which package or library you used.

Thanks @naemiamanuel for the review. I do think that @marianortt is using all base R functions (which is what I prefer) and I think his coding style is to use base R functions first before using any dependency (or use dependency only when needed).

Great work!

@marianortt, I will approve this pull request now. Please merge to main at your convenience.

**Review by ernestguevarra — APPROVED** [review]

**Comment by marianortt** [comment]
I cannot merge due to a conflict, I do not understant what should I do

**Comment by ernestguevarra** [comment]
> I cannot merge due to a conflict, I do not understant what should I do

I sorted the conflict. Feel free to merge when you are ready.

**Pull request merged**
