### PR TITLE
plot rain over time

### PR DESCRIPTION
**Pull request by Bokchol**
kindly check the plot of rain over time, thanks

### CODE REVIEW

**Comment by ernestguevarra** [comment]
this PR seems to fix #17

**Review by ernestguevarra — CHANGES_REQUESTED** [review]
@Bokchol, looks good.

I have a request for minor change. Please avoid using a `.` in your object names as this has a special meaning in R. The objects will still work but sometimes it can cause issues especially when you are using S3 syntax in coding.

An optional challenge for you is to show trend plot (trend only based on your decomposition) for cases and rain on the same plot. I will assign this task to someone else but I want you to try this out yourself as well.

**Comment by Bokchol** [comment]
Kindly check the  changes on the malaria data @ernestguevarra

**Review by ernestguevarra — APPROVED** [review]
@Bokchol your script to show rain and cases time series looks good! Your ggplot that shows both rain and cases data on a time series looks good as well! well done!

**Comment by ernestguevarra** [comment]
@Bokchol please merge your pull request at your convenience

**Pull request merged**
